name: "Example Workflow"

on:
  issues:
    types: [ labeled ]

jobs:
  extract-using-default-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Using defaults
        uses: paulschuberth/regex-extract-action@v2
        id: example-default
        with:
          haystack: ${{ github.event.issue.body }}
    outputs:
      issues: ${{ steps.example-default.outputs.matches }}

  use-default-matches:
    runs-on: ubuntu-latest
    needs: [ extract-using-default-settings ]
    strategy:
      matrix:
        issue: ${{ fromJson(needs.extract-using-default-settings.outputs.issues) }}
    steps:
      - name: Use output of default settings
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Found issue ${{ matrix.issue }}`
            })
